name: cache_service
description: Cache Service is a Flutter package that efficiently caches images and PDFs, including in-memory caching, to reduce load times and resource use for a smoother app experience.
version: 1.0.3
repository: https://github.com/asmit-gupta/cache_services

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dio: ^5.5.0+1
  logger: ^2.4.0
  hive_flutter: ^1.1.0
  syncfusion_flutter_pdfviewer: ^26.2.8
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  assets:
    - lib/src/assets/
    - lib/src/assets/placeholder_image.png